---
- name:  This play is to install apache2
  hosts: app
  become: yes
  tasks:      
  - name: Install Apache2 on Ubuntu 
    apt: 
     name: apache2 
     state: present
  - name: Start apache2
    service: 
      name: apache2
      state: restarted
