- hosts: app
  become: yes
  become_user: root
  tasks:
    - name: change directory to /app
      shell: cd /app

    - name: install wget git java and unzip
      yum:
        name: ['wget', 'git', 'unzip',  'java-1.8.0-openjdk-devel', 'tar', 'nano' ]
        state: present
        update_cache: true

    - name: create /app/nexus directory
      file:
        path: /app/nexus
        state: directory

    - name: Download and Unarchive/ unzip nexus
      ansible.builtin.unarchive:
              src:  http://download.sonatype.com/nexus/3/nexus-3.15.2-01-unix.tar.gz
              dest: /app/nexus
              remote_src: yes

    - name: Add a nexus user
      shell: useradd nexus

    - name: Give sudo rights to nexus user
      shell: echo "nexus ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nexus

    - name: Recursively change ownership and permission of /app/nexus/
      file:
         dest: /app/nexus/
         owner: nexus
         group: nexus
         mode: 0775
         recurse: yes
    - name: Recursively change ownership and permission of /app/sonatype-work
      file:
         dest: /app/sonatype-work
         owner: nexus
         group: nexus
         mode: 0775
         recurse: yes

    - name: Create nexus as a service
      shell: ln -s /app/nexus/bin/nexus /etc/init.d/nexus

    - name: switch user to nexus
      shell: echo "run_as_user=nexus" >> /app/nexus/nexus-3.15.2-01/bin/nexus.rc
      become: yes
      become_user: nexus

    - name: start nexus service
      shell: sh /app/nexus/nexus-3.15.2-01/bin/nexus start
      become: yes
      become_user: nexus


